// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAr7pXUiMw4LgRuE81FSEwmymw3H12Xxg',
    appId: '1:340538984801:web:02408b5cfc1f415ca81d20',
    messagingSenderId: '340538984801',
    projectId: 'kigali-directory-app-50434',
    authDomain: 'kigali-directory-app-50434.firebaseapp.com',
    storageBucket: 'kigali-directory-app-50434.firebasestorage.app',
    measurementId: 'G-2YMM0EZ2G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwMBwGK9CcedQDCQy1J8jCGAgg5QERSqI',
    appId: '1:340538984801:android:a65c84c6aac7131fa81d20',
    messagingSenderId: '340538984801',
    projectId: 'kigali-directory-app-50434',
    storageBucket: 'kigali-directory-app-50434.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_K_0e_wMYcVN66VsoD7Doq5pG2CJQtQ',
    appId: '1:340538984801:ios:4ed5c939f44f6e02a81d20',
    messagingSenderId: '340538984801',
    projectId: 'kigali-directory-app-50434',
    storageBucket: 'kigali-directory-app-50434.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_K_0e_wMYcVN66VsoD7Doq5pG2CJQtQ',
    appId: '1:340538984801:ios:4ed5c939f44f6e02a81d20',
    messagingSenderId: '340538984801',
    projectId: 'kigali-directory-app-50434',
    storageBucket: 'kigali-directory-app-50434.firebasestorage.app',
    iosBundleId: 'com.example.kigaliDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAr7pXUiMw4LgRuE81FSEwmymw3H12Xxg',
    appId: '1:340538984801:web:54634c09cbe214dca81d20',
    messagingSenderId: '340538984801',
    projectId: 'kigali-directory-app-50434',
    authDomain: 'kigali-directory-app-50434.firebaseapp.com',
    storageBucket: 'kigali-directory-app-50434.firebasestorage.app',
    measurementId: 'G-XW47Z83S84',
  );
}
